import { initHostFixture } from './framework/host'

describe(`Common`, () => {
  it(`should print list generated by ngFor`, () => {
    const fixture = initHostFixture({
      props: {
        trackById: (index, item) => item.id,
        items: [
          { id: 1, text: 'text1' },
          { id: 2, text: 'text2' },
          { id: 3, text: 'text3' },
          { id: 4, text: 'text4' },
        ]
      },
      template:
        `<div
          *ngFor="let item of items; trackBy: trackById"
        >
          <div>{{item.text}}</div>
        </div>`
    })

    expect(fixture).toMatchSnapshot()
  })

  it('should print embedded views', () => {
    const fixture = initHostFixture({
      props: {
        context: { $implicit: 'World', localSk: 'Svet' }
      },
      template:
        `<ng-container *ngTemplateOutlet="hello"></ng-container>
        <ng-container *ngTemplateOutlet="helloEng; context: context"></ng-container>
        <ng-container *ngTemplateOutlet="helloSvk; context: context"></ng-container>
        <ng-template #hello><span>Hello!</span></ng-template>
        <ng-template #helloEng let-name><span>Hello {{name}}!</span></ng-template>
        <ng-template #helloSvk let-world="localSk"><span>Ahoj {{world}}!</span></ng-template>`
    })

    expect(fixture).toMatchSnapshot()
  })
})
